### ISSUE TITLE
建议作者完善项目说明

### ISSUE THREAD

**Issue by idawnchen** [pipijoe/user_auth#1]
我是在简书上看到SpringSecurity和JWT集成的文章定位到git上来的，我下下来后，完整的看了一眼代码，项目也跑起来了，但是当我想打开swagger时，发现提示没权限。
README中对项目的说明很少，只能自己去摸索，建议作者对代码，特别是类的作用加一些注释，让新手更加容易明白
感谢作者的辛苦付出！

**Comment by pipijoe** [comment]
你好，谢谢你的建议和支持。
项目里使用spring rest docs替代了swagger做接口说明。可以查看rest docs的相关文档。web ui地址是ip:port/index.html
项目还有很多需要完善的地方，等工作空闲会抽时间再继续完善。
